### ISSUE TITLE
building for ubuntu

### ISSUE THREAD

**Issue by ali4ever4** [neka-nat/python-forexconnect#11]
Hi tried to build for ubuntu

but get this error when try to import the library

ImportError: /usr/local/lib/python2.7/dist-packages/forexconnect.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

**Comment by neka-nat** [comment]
Hi, ali4ever4.
I guess you don't install boost-python or set path for boost-python libraries.
Please, try the following command.
```
sudo apt-get install build-essential cmake libboost-log-dev libboost-date-time-dev libboost-python-dev
```

**Comment by ali4ever4** [comment]
Hi,

they were already installed 

Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
cmake is already the newest version.
libboost-date-time-dev is already the newest version.
libboost-log-dev is already the newest version.
libboost-python-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 128 not upgraded.

**Comment by neka-nat** [comment]
I guess your environment cannot find boost-python libraries.
You have to find boost-python libraries and add the path to LD_LIBRARY_PATH.
