### ISSUE TITLE
FXCM Data Miner

### ISSUE THREAD

**Issue by JamesKBowler** [neka-nat/python-forexconnect#13]
Hi team,

Just thought I would pop in and say, I have written a python program to download all of FXCM's data, both historical and live.

My next move is to integrate QSTrader with FXCMs API.

You can find fxcmminer at the link below.... be nice its my first one!
https://github.com/JamesKBowler/fxcmminer

Thank-you

Regards

James

**Comment by neka-nat** [comment]
Hi JamesKBowler,

It's very cool!
I appreciate your utilizing our library.
If there's anything I can help with about this library, please let me know.

Thank you.

**Comment by JamesKBowler** [comment]
Hi neka-nat,
My pleasure and thank-you for making this python API available!
I'm sure I will more questions once I get going with QSTrader integration.

Regards
James
