### ISSUE TITLE
Time Zones

### ISSUE THREAD

**Issue by JamesKBowler** [neka-nat/python-forexconnect#14]
Hi,
Please could you confirm if this part of code is removed all the time stamps will not be adjusted to the system time?

If this is correct the data called via the API will be exaclty how FXCM store their data?

For example if this line is removed from `ForexConnectClient.h.in`
`return boost::date_time::c_local_adjustor<boost::posix_time::ptime>::utc_to_local(boost::posix_time::from_time_t(t));`

and replaced for this?
`return boost::posix_time::from_time_t(t);`

Thanks

James

**Comment by neka-nat** [comment]
Hi,
I think all the time stamps will be adjusted to the system time by replacing the code.
Did you mean you tried it and the time stamps was not adjusted to the system time?
Can I see the data?

Regards,
nekanat

**Comment by JamesKBowler** [comment]
Hi NekaNat,
Appreciate your quick response.

Yeah I replaced the line of code and the time stamps come back as UTC which is what I want and expected. 
I initially thought FXCM Data was stored in EST,  however thats incorrect and I received confirmation from the FXCM api team today. They also said even though time is stored in UTC, there is an offset of one hour to account for the New York open in Summer and Winter. 
I don't understand how FXCM can say it's UTC with US/Eastern time zone DST offset.

My thinking is that when data is written to a database there should be no DST offset. What is your view on this?

Thanks 

James

**Comment by JamesKBowler** [comment]
Think I understand the offset now. There are two elements at play here DST and New York open times for Summer and Winter.
http://www.babypips.com/school/preschool/when-can-you-trade-forex/trading-sessions.html

You can close this one

Thanks 

James

**Comment by neka-nat** [comment]
Thank you for examining about time zone.
I also knew this for the first time.

Regards,
nekanat
