### ISSUE TITLE
Boost Version

### ISSUE THREAD

**Issue by joaofranca** [neka-nat/python-forexconnect#2]
Can you specify which boost version you are using?

**EDIT:**
Instead of manually compiling the boost library, I installed it with
_sudo apt-get install libboost-log-dev libboost-date-time-dev libboost-python-dev_
and everything just got working fine.

**Comment by neka-nat** [comment]
I confirmed compiling boost 1.54.
If the OS you use is ubuntu 14.04, boost version is 1.54.

I will add version of used libraries to README. 
Thank you.
