### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ghost** [neka-nat/python-forexconnect#21]
client reported below error
sudo python2 test2.py 
Traceback (most recent call last):
  File "test2.py", line 1, in <module>
    import forexconnect
ImportError: libsample_tools.so: cannot open shared object file: No such file or directory

**Comment by neka-nat** [comment]
I guess environment setting is not enough.
Please set the directory where libsample_tools.so is located to LD_LIBRARY_PATH.

```
export LD_LIBRARY_PATH=LD_LIBRARY_PATH:<your python-forexconnect path>/lib
```

**Comment by ghost** [comment]
Thank you Neka-nat
Let me inform client
