### ISSUE TITLE
Install documentation

### ISSUE THREAD

**Issue by josephernest** [neka-nat/python-forexconnect#4]
Hi! I spent more than 1 hour trying unsuccessfully to install this module.
Until I found this very useful [step-by-step guide](https://github.com/neka-nat/python-forexconnect/issues/1#issuecomment-179786035).  
Could you mention a link to this on the main README.md ?

**Comment by neka-nat** [comment]
Sorry, josephernest.
I added the detail guide to README.rst.
Thank you.

**Comment by josephernest** [comment]
Thanks a lot!
In:

```
cmake .. -DDEFAULT_FOREX_URL="http://<Your forexconnect URL>"
```

what do you mean by `"http://<Your forexconnect URL>"` ?

I used:

```
cmake ..
```

as mentionned [here](https://github.com/neka-nat/python-forexconnect/issues/1#issuecomment-179786035) and it works.

**Comment by neka-nat** [comment]
`http://<Your forexconnect URL>` means the url to use forexconnect api.
It is necessary to login in [the original c++ api](http://fxcodebase.com/wiki/index.php/Login_in_ForexConnect_%28C%2B%2B%29) and differs by each users.

**Comment by josephernest** [comment]
Can you give an example of such URL? Where do you find it in FXCM?

I only used `cmake ..`  and _not_ `cmake .. -DDEFAULT_FOREX_URL="..."` but still it worked.  
The login happens when I do `cl = forexconnect.ForexConnectClient("usrname", "pass", "Real")`.

**Comment by neka-nat** [comment]
Default url is "http://www40.fxcorporate.com/Hosts.jsp".
I think your account's url is the default url.

An example of the url is [here](http://fxcodebase.com/wiki/index.php/Login_in_ForexConnect_%28C%2B%2B%29#Log_In).

**Comment by josephernest** [comment]
Thanks!
