### ISSUE TITLE
Do you have plan to imporve the API?

### ISSUE THREAD

**Issue by 4ever911** [neka-nat/python-forexconnect#5]
for example:

1.Streaming Price quotes
2.Order Type support, only market orders now
3.Close part of the positions
4.call back /event to notify python that something has changed, such as order table, price...etc.
5. etc...

**Comment by neka-nat** [comment]
Hi, 4ever911.
I have had plan to implement some functions of your requests.
But, I don't set the implementation schedule.
If you have a request for priority, I consider implementation and schedule.
Thanks you.

**Comment by 4ever911** [comment]
I am tring to create a python based FXCM trading software for my own. The problem is that i have to manually get the price changes by for loop, it's not event driving.

As well the order types, it's also very important for placing an order.

I guess not only me, but also a lot of users who use this library need those functions. 
Anyway, I still think this is the best python wrap so far. Thank you for your contribution.
