### ISSUE TITLE
pthreads in windows

### ISSUE THREAD

**Issue by stefan160** [neka-nat/python-forexconnect#8]
Hi neka-nat

nice work! I like your library. It is plain and easy in use and its working perfectly in Linux, but recently i tried to compile it for windows. Unfortunatly pthreads.h is missing in MSVC, even if it shouldnt look for it in windows. Have you tried to compile it for windows? 

I'm using: Python 3.5, Boost 1.62, MSVC 14, Cmake 3.7, Windows 10 

Thanks for your great work!

**Comment by neka-nat** [comment]
Hi stefan160.
I tried to compile and fixed the source for windows.
Can you try to compile the latest master for windows?

First, you have to compile the only sample_tools using python-forexconnect/forexconnect/sample_tools/sample_tools.vcproj,
and next, compile the pyforexconnect using cmake.
Thank you.
